"""FR1 / FA-3 -- field laws over p = 101."""
import pytest

pytestmark = pytest.mark.skip(reason="FA-1/FA-2 not implemented yet")


def test_associativity(field): ...
def test_commutativity(field): ...
def test_distributivity(field): ...
def test_additive_and_multiplicative_identity(field): ...
def test_reduction_of_negative_and_large_integers(field): ...
