"""FR3 / CT-3 -- algebraic identities over p = 101."""
import pytest

pytestmark = pytest.mark.skip(reason="CT-2 not implemented yet")


def test_A_plus_zero_equals_A(field): ...
def test_A_times_identity_equals_A(field): ...
def test_double_transpose_is_identity(field): ...
def test_transpose_of_product(field): ...
