"""FR4 / LA-1 -- schoolbook multiplication."""
import pytest

pytestmark = pytest.mark.skip(reason="LA-1 not implemented yet")


def test_hand_computed_2x2(field): ...
def test_hand_computed_3x3(field): ...
def test_dimension_mismatch_raises_ShapeError(field): ...
def test_same_result_at_both_primes(any_field): ...
